export interface Candidate {
      "id": number,
      "name": string,
      "email": string,
      "electoralKey": string,
      "fathersLastName": string,
      "mothersLastName": string,
      "power": string,
      "charge": string,
      "subcharge": string,
      "subcharge2": string,
      "phone":string,
      "username":string,
      "password":string,
      "createdBy"?: any[],
}